version: "3"
services:
  node:
    container_name: node-container
    build: ./docker/node
    volumes:
      - ./app:/var/app
  apache:
    container_name: apache-container
    build: ./docker/apache
    ports:
      - "80:80"
    volumes:
      - ./app/public:/usr/local/apache2/htdocs
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '443:443'
    environment:
      STAGE: local
      DOMAINS: 'localhost -> http://apache:80'
